name: 'Setup Environment'
description: 'Sets up Python, uv, and dependencies'
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"

    - name: Set up uv
      uses: astral-sh/setup-uv@v8.1.0
      with:
        version: "latest"

    - name: Install dependencies
      shell: bash
      run: |
        uv venv --seed
        uv sync --all-extras
