name: Run Tests

on:
  push:
    branches: [ "master", "release", "develop" ]
  pull_request:
    branches: [ "master", "release", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup Python environment
      uses: ./.github/actions/setup-env

    - name: Install project as editable
      run: uv pip install -e ".[dev]"

    - name: Run tests with pytest
      run: uv run pytest tests/
